### ISSUE TITLE
Link to demo page is broken

### ISSUE THREAD

**Issue by spiralx** [bmcmahen/image-zoom#13]
The link to the demo page [benmcmahen.com/image-zoom/index.html](http://benmcmahen.com/image-zoom/index.html) is broken and gives a site not found error. The URL [bmcmahen.github.io/image-zoom](http://bmcmahen.github.io/image-zoom) takes you to the page however, so replacing the links with that URL would fix it :)

**Comment by bmcmahen** [comment]
Nice catch. I'll update it. thanks.

**Comment by oyeanuj** [comment]
@bmcmahen The link is still broken in the Readme : http://benmcmahen.com/image-zoom/index.html

The link in the headline description works though..

**Comment by bmcmahen** [comment]
Thanks. Fixed it.
