### ISSUE TITLE
Loading Animation ?

### ISSUE THREAD

**Issue by twistintale** [bmcmahen/image-zoom#14]
I really love your plug-in. Simple, light and no-blurry images !
Can you throw me some ideas about how to add css loading effects.

**Comment by bmcmahen** [comment]
It should add a `loading` class to the thumbnail when it's loading. You could use that to perhaps display a loading indicator, or alter the opacity of the thumbnail while loading.

```
.loading:before {
  content: '';
  icon: 'something';
}
```

```
.loading {
  opacity: 0.3;
}
```

You could also listen for the loading event if you're using the javascript api. 

```
zoom.on('loading', function(el) {
  // do something with el
})
```

I've never really utilized a loading indicator for my uses, but this should give you some ideas to get started.
